services:
  dockpeek:
    image: dockpeek/dockpeek:latest
    container_name: dockpeek
    
    ports:
      - "3420:8000"
      
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - USERNAME=${USERNAME}
      - PASSWORD=${PWD}

      # --- Docker Host 1 ---
      - DOCKER_HOST_1_URL=unix:///var/run/docker.sock # Local Docker socket
      #- DOCKER_HOST_1_URL=tcp://${HOST_IP_1}:2375
      - DOCKER_HOST_1_NAME=${HOSTNAME_1} Docker                # is Optional: Auto-detected from Docker API if not set
      - DOCKER_HOST_1_PUBLIC_HOSTNAME=${HOSTNAME_1}.local      # is optional; uses host IP by default

      # --- Docker Host 2 ---
      - DOCKER_HOST_2_URL=tcp://${HOST_IP_2}:2375              # Remote socket proxy
      - DOCKER_HOST_2_NAME=${HOSTNAME_2} Docker                # Optional: Auto-detected from Docker API if not set
      - DOCKER_HOST_2_PUBLIC_HOSTNAME=${HOSTNAME_2}.local      # Optional: Custom hostname for links

      # --- Docker Host 3 ---
      - DOCKER_HOST_3_URL=tcp://${HOST_IP_3}:2375
      - DOCKER_HOST_3_NAME=${HOSTNAME_3} Docker
      - DOCKER_HOST_3_PUBLIC_HOSTNAME=${HOSTNAME_3}.local

      # --- Docker Host 4 ---
      - DOCKER_HOST_4_URL=tcp://${HOST_IP_4}:2375
      - DOCKER_HOST_4_NAME=${HOSTNAME_4} Docker
      - DOCKER_HOST_4_PUBLIC_HOSTNAME=${HOSTNAME_4}.local
      
      # --- Docker Host 3 (Tailscale) ---
      #- DOCKER_HOST_3_URL=tcp://100.64.1.5:2375 # Tailscale IP
      #- DOCKER_HOST_3_NAME=Remote VPS # Optional: Auto-detected from Docker API if not set
      #- DOCKER_HOST_3_PUBLIC_HOSTNAME=vps.tailnet.ts.net # Optional: Tailscale FQDN

      # --- Continue pattern for additional hosts (4, 5, etc.) ---
    volumes:
      # Required only if you are connecting to a local socket
      - /var/run/docker.sock:/var/run/docker.sock:ro

    restart: unless-stopped
    
