# Run with docker compose up -d
services:
  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      # <Host Port>:<Container Port>
      - ${DOZZLE_PORT}:8080
    environment:
      # Uncomment to enable container actions (stop, start, restart). See https://dozzle.dev/guide/actions
      - DOZZLE_ENABLE_ACTIONS=true
      #
      # Uncomment to allow access to container shells. See https://dozzle.dev/guide/shell
      - DOZZLE_ENABLE_SHELL=true
      #
      # Uncomment to enable authentication. See https://dozzle.dev/guide/authentication
      # - DOZZLE_AUTH_PROVIDER=simple
      #
      # Hostname
      - DOZZLE_HOSTNAME=${HOSTNAME}
      #
      # Remote hosts
      - DOZZLE_REMOTE_AGENT=${HOST_IP_2}:${DOZZLE_AGENT_PORT},${HOST_IP_3}:${DOZZLE_AGENT_PORT},${HOST_IP_4}:${DOZZLE_AGENT_PORT}
